name: flutter_map_marker_cluster
description: A Dart implementation of Leaflet.makercluster for Flutter apps.
  Provides beautiful animated marker clustering functionality for flutter_map.
version: 1.1.1

homepage: https://github.com/lpongetti/flutter_map_marker_cluster

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_map_marker_popup:
    git:
      url: git@github.com:p30arena/flutter_map_marker_popup.git
      ref: master
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
